import type { NextPage } from 'next';
import Head from 'next/head';
import { ListPlanet } from 'components/list-planet';
import { ListContainer } from 'components/template/list';
import { BodyContainer } from 'components/template/body-container';
import Image from 'next/image';
import { Footer, FooterLogo } from 'components/template/footer';
import IPlanet from 'dto/planet';
import getList from 'helpers/wishlist';
import { useEffect, useState } from 'react';

const WishList: NextPage = () => {
  const [planets, setPlanets] = useState<IPlanet[]>([]);
  useEffect(() => {
    setPlanets(getList());
  }, []);

  return (
    <BodyContainer>
      <Head>
        <title>Test Frontend Developer React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ListContainer role="list">
        {planets.length > 0 ? (
          planets.map((planet: IPlanet, idx) => <ListPlanet planet={planet} key={idx} />)
        ) : (
          <li>There is no Wishlist</li>
        )}
      </ListContainer>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <FooterLogo>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </FooterLogo>
        </a>
      </Footer>
    </BodyContainer>
  );
};

export default WishList;
